-- GitLab and GitHub CI/CD integration setup with workload identity for Snowflake
-- Co-authored with CoCo
USE ROLE ACCOUNTADMIN;
USE DATABASE PLANT_SHOP;
USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_WH;

CREATE USER IF NOT EXISTS gitlab_cicd_user
  TYPE = SERVICE
  DEFAULT_WAREHOUSE = 'COMPUTE_WH_PLANT_SHOP'
  DEFAULT_NAMESPACE = 'PLANT_SHOP.PUBLIC'
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://gitlab.com'
    SUBJECT = 'project_path:daimonie/snowflake-ci:ref_type:branch:ref:main'
  );

CREATE USER IF NOT EXISTS github_cicd_user
  TYPE = SERVICE
  DEFAULT_WAREHOUSE = 'COMPUTE_WH_PLANT_SHOP'
  DEFAULT_NAMESPACE = 'PLANT_SHOP.PUBLIC'
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:daimonie@10976353/snowflake-ci@1339604377:ref:refs/heads/main'
  );

ALTER USER gitlab_cicd_user SET DEFAULT_WAREHOUSE = 'COMPUTE_WH_PLANT_SHOP' DEFAULT_NAMESPACE = 'PLANT_SHOP.PUBLIC';
ALTER USER github_cicd_user SET DEFAULT_WAREHOUSE = 'COMPUTE_WH_PLANT_SHOP' DEFAULT_NAMESPACE = 'PLANT_SHOP.PUBLIC';


CREATE TABLE IF NOT EXISTS log AS
SELECT 'new table!' AS message, CURRENT_TIMESTAMP() as time_col;

ALTER TABLE plant_shop.public.log MODIFY COLUMN message VARCHAR(256);
CREATE ROLE IF NOT EXISTS GIT_CICD;

-- Database and schema usage (read-only at db/schema level)
GRANT USAGE ON DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;

-- Read/write on tables (existing and future)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;

-- Note: ALTER TABLE requires OWNERSHIP, which cannot be bulk-granted.
-- Run schema changes (ALTER TABLE MODIFY COLUMN, etc.) as ACCOUNTADMIN, not via CI.

-- Create tables/views within schemas
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH_PLANT_SHOP TO ROLE GIT_CICD;

GRANT CREATE PROCEDURE ON ALL SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;
GRANT CREATE PROCEDURE ON FUTURE SCHEMAS IN DATABASE PLANT_SHOP TO ROLE GIT_CICD;

-- Assign role to CI/CD users
GRANT ROLE GIT_CICD TO USER gitlab_cicd_user;
GRANT ROLE GIT_CICD TO USER github_cicd_user;
GRANT ROLE GIT_CICD TO USER DAIMONIE;

SELECT CURRENT_ACCOUNT();